import java.awt.Color;

import java.util.List;
import javax.swing.JOptionPane;


public class softwareDownload extends javax.swing.JFrame {
    
    GetSetBD db = new GetSetBD();
    MulticastCl ClienteMulticast = new MulticastCl(db);
    MulticastVerifServidor ClienteMulticastCheck = new MulticastVerifServidor(db);
    RMIcl ClienteRMI = new RMIcl(db, this);
    UnicastCl ClienteUnicast = new UnicastCl(db, this);

    /**
     * Creates new form Client
     */
    public softwareDownload() {
        initComponents();
        System.out.println("El Software ha sido iniciado. ↑ \n ");
        System.out.print("Cliente Multicast inicializado. ↑\n");
        System.out.print("Cliente Multicast CL inicializado. ↑\n");
        System.out.print("Cliente RMI inicializado. ↑\n");
        System.out.println("Cliente Unicast inicializado. ↑\n ");
        ClienteMulticast.start();
        ClienteMulticastCheck.start();
        ClienteRMI.start();
        ClienteUnicast.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inputFileName = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(550, 314));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFileNameActionPerformed(evt);
            }
        });
        getContentPane().add(inputFileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 270, 30));

        btnBuscar.setFont(new java.awt.Font("VL Gothic", 0, 13)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 40, 40));

        btnDownload.setBackground(new java.awt.Color(255, 255, 255));
        btnDownload.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnDownload.setForeground(new java.awt.Color(253, 212, 228));
        btnDownload.setText("Descargar");
        btnDownload.setEnabled(false);
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        getContentPane().add(btnDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 160, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IPN.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ESCOM.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Console", 0, 12)); // NOI18N
        jLabel4.setText("Ingresa nombre del archivo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("NSimSun", 1, 30)); // NOI18N
        jLabel2.setText("Búsqueda de archivos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, -1));

        jPanel1.setBackground(new java.awt.Color(253, 238, 244));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(253, 223, 234), new java.awt.Color(255, 204, 204)));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       //Verificar que en la db haya al menos 1 servidor
       List<serverData> ServersList = db.getServidores();
       if(ServersList.size() != 0){
           ClienteRMI.buscaArchivo(inputFileName.getText());
       }else{
           JOptionPane.showMessageDialog(null,  "Servidor no disponible ¤" , "Busqueda", JOptionPane.WARNING_MESSAGE);
       }
      
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        System.out.println("Archivo a descargar: "+db.getArchivoEncontrado().getPath().toString());
        System.out.println("Servidor: "+db.getArchivoEncontradoServ());
        //Nos conectamos
        ClienteUnicast.conectaServidor();
        ClienteUnicast.descargaArchivo();
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void inputFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFileNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(softwareDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(softwareDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(softwareDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(softwareDownload.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new softwareDownload().setVisible(true);
            }
        });
    }
    
    public void changeDownload(boolean b){
        btnDownload.setEnabled(b);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDownload;
    private javax.swing.JTextField inputFileName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
